const constants = {
  FETCHING_AT: 'FETCHING_AT',
  CANCEL_FETCHING_AT: 'CANCEL_FETCHING_AT',
  GET_AIR_TEMP: 'GET_AIR_TEMP',

  FETCHING_CUR: 'FETCHING_CUR',
  CANCEL_FETCHING_CUR: 'CANCEL_FETCHING_CUR',
  GET_CURRENTS: 'GET_CURRENTS',

  FETCHING_WS_ABOVE_DATUM: 'FETCHING_WS_ABOVE_DATUM',
  CANCEL_FETCHING_WS_ABOVE_DATUM: 'CANCEL_FETCHING_WS_ABOVE_DATUM',
  GET_WS_ABOVE_DATUM: 'GET_WS_ABOVE_DATUM',

  FETCHING_OCEAN_TIDE: 'FETCHING_OCEAN_TIDE',
  CANCEL_FETCHING_OCEAN_TIDE: 'CANCEL_FETCHING_OCEAN_TIDE',
  GET_OCEAN_TIDE: 'GET_OCEAN_TIDE',

  FETCHING_WATER_TEMP: 'FETCHING_WATER_TEMP',
  CANCEL_FETCHING_WATER_TEMP: 'CANCEL_FETCHING_WATER_TEMP',
  GET_WATER_TEMP: 'GET_WATER_TEMP',

  FETCHING_WIND: 'FETCHING_WIND',
  CANCEL_FETCHING_WIND: 'CANCEL_FETCHING_WIND',
  GET_WIND: 'GET_WIND',

  FETCHING_VIS: 'FETCHING_VIS',
  CANCEL_FETCHING_VIS: 'CANCEL_FETCHING_VIS',
  GET_VIS: 'GET_VIS',

  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',

  GET_LOC: 'GET_LOC',
  GET_DATA: 'GET_DATA',
  

  /* ADD_DAY: "ADD_DAY",
REMOVE_DAY: "REMOVE_DAY",
SET_GOAL: "SET_GOAL",
ADD_ERROR: "ADD_ERROR",
CLEAR_ERROR: "CLEAR_ERROR",
FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
CANCEL_FETCHING: "CANCEL_FETCHING",
CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS" */
}

export default constants