const constants = {
  FETCHING: 'FETCHING',
  CANCEL_FETCHING: 'CANCEL_FETCHING',
  ADD_ERROR: 'ADD_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  GET_LOC: 'GET_LOC',
  GET_DATA: 'GET_DATA',

  /* ADD_DAY: "ADD_DAY",
REMOVE_DAY: "REMOVE_DAY",
SET_GOAL: "SET_GOAL",
ADD_ERROR: "ADD_ERROR",
CLEAR_ERROR: "CLEAR_ERROR",
FETCH_RESORT_NAMES: "FETCH_RESORT_NAMES",
CANCEL_FETCHING: "CANCEL_FETCHING",
CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS" */
}

export default constants